apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-utility-app5g0010
spec:
  accessModes: [ "ReadWriteMany" ]
  selector:
    matchLabels:
      special: 10
  resources:
    requests:
      storage: 2Gi
