apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gce1
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
