apiVersion: v1
kind: Pod
metadata:
  name: rhel
spec:
  hostPID: true
  hostIPC: true
  hostNetwork: true
  hostname: toor
  # nodeSelector:
  #   kubernetes.io/hostname: node3.novalocal
  # nodeName: node3.novalocal
  volumes:
    - name: host
      hostPath:
        path: /
    - name: run
      hostPath:
        path: /run
    - name: log
      hostPath:
        path: /var/log
    - name: localtime
      hostPath:
        path: /etc/localtime
  containers:
    - name: rhel
      image: rhel7/rhel-tools
      command: [ "/bin/sh", "-c", "while true ; do date; sleep 1; done;" ]
      securityContext:
        privileged: true
      env:
        - name: HOST
          value: "/host"
        - name: NAME
          value: "toor"
        - name: IMAGE
          value: "rhel/rhel-tools"
      volumeMounts:
        - name: host
          mountPath: /host
        - name: run
          mountPath: /run
        - name: log
          mountPath: /var/log
        - name: localtime
          mountPath: /etc/localtime
  restartPolicy: Never
